name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # 最新バージョンを確認し、必要なら更新
      - name: Set up Node.js
        uses: actions/setup-node@v3  # Node.js 20に対応したバージョンがあれば更新
        with:
          node-version: '20.10.0'  # 必要に応じてバージョンを指定
      - run: npm install
      - run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3  # 最新バージョンに更新
        with:
          name: htdocs
          path: htdocs/  # distからhtdocsに変更

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3  # 最新バージョンに更新
      - name: Download Artifacts
        uses: actions/download-artifact@v3  # 最新バージョンに更新
        with:
          name: htdocs  # distからhtdocsに変更
          path: htdocs/  # distからhtdocsに変更
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEV_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - name: Deploy to Server
        env:
          DEV_USER: ${{ secrets.DEV_USER }}
          DEV_DOMAIN: ${{ secrets.DEV_DOMAIN }}
          DEV_DIR: ${{ secrets.DEV_DIR }}
        run: |
          ssh -i ~/.ssh/id_rsa $DEV_USER@$DEV_DOMAIN "mkdir -p $DEV_DIR"
          rsync -rltoDv -e "ssh -i ~/.ssh/id_rsa" --delete --checksum htdocs/ $DEV_USER@$DEV_DOMAIN:$DEV_DIR
